config/routes.rb
Speciality::Application.routes.draw do
  devise_for :users,
    :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  match '/rate' => 'rater#create', :as => 'rate'
  match 'dish_autocompleter' => "home#dish_autocompleter"
  match 'tag_autocompleter' => "home#tag_autocompleter"
  match 'place_autocompleter' => "home#place_autocompleter"
  match 'place_autocompleter' => "home#place_autocompleter"
  match "search" => "search#index"
  resources :locations

  resources :reviews

  resources :tags do
    collection do
      get :search
    end
  end

  resources :restaurants do
    collection do
      get :search
    end
  end

  resources :dishes do
    get :show_image
    get :show_small_image
  end

  resources :users

  root :to => 'home#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	searchkick autocomplete: ['name']
	attr_accessible :avg_ratings, :description, :location_id, :name,
			:no_of_ratings, :restaurant_id, :user_id, :tag_names, :restaurant_name, :attachment,:cost
	attr_accessor :tag_names, :restaurant_name, :score
	belongs_to :user
	belongs_to :location
	belongs_to :restaurant
	has_many :reviews
	has_many :tag_dishes
	has_many :tags, :through => :tag_dishes
	has_many :searches
	delegate :name, :to => :restaurant, :allow_nil => true, :prefix => true
	delegate :address, :to => :location, :allow_nil => true, :prefix => true
  delegate :avatar, :to => :attachment, :allow_nil => true
  letsrate_rateable "awesomeness"

  has_one :attachment, :as => :attachable, :dependent => :destroy


	scope :search_import,includes([:tag_dishes,:tags, :location])
	scope :find_recent_dishes, lambda { |items|
		order("created_at DESC").limit(items)
	}
	scope :include_tags, includes([:tags, :restaurant, :attachment, :location])

  after_create :add_dish_rating

	def search_data
		{
			tag: tags.collect(&:name),
			name: name,
			location: location.address
		}
	end

	def total_ratings
		avg_ratings.present? && no_of_ratings.present? ? avg_ratings * no_of_ratings : 0
	end

	before_save :build_new_tags
	validates :restaurant_id, :presence => :true
	validates :name, :presence => :true
  validates :score, :presence => :true, :on => :create
	validates :cost, :presence => :true, :numericality => {:only_integer_and_float => true}

	def self.recently_added
		Dish.find(:all, :include => :location, :order => "id desc", :limit => 8)
	end

	def self.search_all_with_id(ids)
		Dish.find(:all,:conditions => { :id => ids } , :include => :location, :order => "id desc", :limit => 8)
	end

	private
		def build_new_tags
			return if tag_names.blank?
			self.tags.clear
			(tag_names || "").split(",").each do |name|
				tag = Tag.find_or_create_by_name(name)
				self.tags << tag
			end
		end

    def add_dish_rating
      rate(score, user_id, "awesomeness") 
    end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
	before_filter :load_restaurant, :only => [:create, :update]
	# GET /dishes
	# GET /dishes.json
	def index
		@dishes = Dish.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @dishes }
		end
	end

	# GET /dishes/1
	# GET /dishes/1.json
	def show
		@dish = Dish.find(params[:id])
    @reviews = @dish.reviews.all
    @new_review = @dish.reviews.new

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @dish }
		end
	end

  def show_image
    @dish = Dish.find(params[:dish_id])
    send_data @dish.avatar.file_contents(:small), 
      :type => 'image/png', :disposition => 'inline'
  end

  def show_small_image
    @dish = Dish.find(params[:dish_id])
    send_data @dish.avatar.file_contents(:thumb), 
      :type => 'image/png', :disposition => 'inline'
  end

	# GET /dishes/new
	# GET /dishes/new.json
	def new
		@dish = current_or_guest_user.dishes.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @dish }
		end
	end

	# GET /dishes/1/edit
	def edit
		@dish = current_or_guest_user.dishes.find(params[:id])
	end

	# POST /dishes
	# POST /dishes.json
	def create
    attachment = params[cname].delete(:attachment)
	  @dish = current_or_guest_user.dishes.build(params[cname])
    @dish.build_attachment(:avatar => attachment)
    @dish.restaurant = @restaurant
    @dish.score = params[:score]

    build_location
		respond_to do |format|
			if @dish.save
				format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
				format.json { render json: @dish.id }
        # format.js
			else
				format.html { render action: "new" }
				format.json { render json: @dish.errors, status: :unprocessable_entity }
        # format.js
			end
		end
	end

	# PUT /dishes/1
	# PUT /dishes/1.json
	def update
		attachment = params[cname].delete(:attachment)
		@dish = current_or_guest_user.dishes.find(params[:id])
		@dish.build_attachment(:avatar => attachment) unless attachment.blank?
		@dish.restaurant = @restaurant
    build_location
		respond_to do |format|
			if @dish.update_attributes(params[:dish])
				format.json { render json: @dish.id }
			else
				format.json { render json: @dish.errors, status: :unprocessable_entity }
			end
		end
    
	end

	# DELETE /dishes/1
	# DELETE /dishes/1.json
	def destroy
		@dish = current_or_guest_user.dishes.find(params[:id])
		@dish.destroy

		respond_to do |format|
			format.html { redirect_to dishes_url }
			format.json { head :no_content }
		end
	end

	def build_location
		@dish.build_location(params[:location])
	end
	
	private
		def load_restaurant
			@restaurant = Restaurant.find_or_create_by_name(params[cname][:restaurant_name])
		end

		def cname
			@cname ||= controller_path.gsub('/', '_').singularize
		end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
	<% if @dish.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

		<ul>
			<% @dish.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<br/>
	<div class="field">
		<%= f.label :user_id %><br />
		<%= f.number_field :user_id %>
	</div>
	<br/>
	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</div>
	<%#= render :partial =>"/locations/form" %>
	<div class="field">
		<%= f.label :restaurant_name %><br />
		<%= f.text_field :restaurant_name, :class => "restaurant_autocomplete select2-input select2-default",
		:'data-id' => @dish.restaurant_id, :'data-text' => @dish.restaurant_name  %>
	</div>
	<br/>
	<div class="field">
		<%= f.label :tag_names %><br />
		<%= f.text_field :tag_names, :class => "tags_autocomplete select2-input select2-default",
		:'data-value' => @dish.tags.map(&:name).join(","), :value => " " %>
	</div>
	<br/>
	<div class="field">
		<%= f.label :avatar %><br />
		<%= f.file_field :attachment %>
	</div>
	<br/>
	<br/>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/dishes/_review.html.erb
<% unless review.new_record? %>
	<div class="reviews">
		<div class="reviewer_image_container">
      <%= foodie_profile_image(review.user, "review", "reviewer_image") %>
			<p class="reviewer_name ellipsis" title='<%= review.user.name %>'><%= review.user.name %></p>
			<p class="reviewer_rating">
				<% rating = review.user.ratings_given.where({
					:dimension => "awesomeness",
					:rateable_id => @dish.id,
					:rateable_type => @dish.class.name }).first %>
				<%= rating.stars unless rating.blank? %>
			</p>
		</div>
		<div class="reviewer_review_content">
			<p class="review_content">
				<%= review.description %>
			</p>
			<p class="review_date">
				<%= time_ago_in_words review.created_at %> ago
			</p>
		</div>
	</div>
<% end %>

app/views/dishes/create.js.erb
var error = $("#new_dish #error_explanation");
<% if @dish.errors.any? %>
  error.append('<ul>');
  <% @dish.errors.full_messages.each do |msg| %>
    error.append("<li><%= msg %></li>");
  <% end %>
  error.append('</ul>');
<% else %>
  $('#new_item_modal').modal('hide');
  error.empty();
  window.location = "<%= dish_path(@dish) %>";
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Location</th>
    <th>Description</th>
    <th>Restaurent</th>
    <th>Avg points</th>
    <th>No of ratings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.name %></td>
    <td><%= dish.user_id %></td>
    <td><%= dish.location_id %></td>
    <td><%= dish.description %></td>
    <td><%= dish.restaurant_id %></td>
    <td><%= dish.avg_ratings %></td>
    <td><%= dish.no_of_ratings %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<%= javascript_include_tag :dishes %>
<div class="container container_item_page">
	<div class="row item_info_box row_modify">
		<div class="col-lg-12 section_item">
			<div class="row row_item">
				<div class="item_same_line">
          <%= rendering_image_data(@dish, "item_info_bar") %>
				</div>
				<div class="item_same_line item_main_info">
					<div class="item_description_div">
						<p class="item_title"><%= @dish.name %></p>
						<p class="item_restaurant"><%= link_to @dish.restaurant_name, restaurant_path(@dish.restaurant) %></p>
						<p class="item_description_content"><%= @dish.description %></p>
						<div class="dish_info_footer">
							<div class="item_same_line_info">
								<span class="info_poster">Posted by : </span>
                <span class="info_poster_name"><%= link_to @dish.user.name,
                 user_path(@dish.user) %></span>
							</div>
							<div class="item_same_line_info">
								<span class="info_poster">Tags : </span>
								<% (@dish.tags || []).each do |tag| %>
									<span class="info_poster_name">
										<%= link_to tag.name.camelcase, search_path('search[tags]' => tag.name)%>
									</span>
								<% end %>
							</div>
							<div class=" black_box black_box_margin">
								<span>RATE THIS DISH<span>
								<div class="ratings_container">
									<%= rating_stars(@dish) %>
								</div>
							</div>
							<div class="black_box">
								<span class="info_poster write_review"><a href="#" >WRITE A REVIEW</a> </span>
								<span class="info_poster_name" style="margin-left:20px;margin-right:20px;">
									<%= @dish.reviews.count > 0 ? "#{@dish.reviews.count} reviews so far" : "Be the first reveiwer" %></span>
							</div>
						</div>
					</div>
					<div class="item_properties_div">
						<div class="item_description_div_points">
							<p class="item_description_div_point">
								<span class="ratings_average"><%= (@dish.avg_ratings || 0.0).to_f.round(1) %></span></p>
							<p class="item_description_div_rating">
								<span class="no_of_people_rated"><%= @dish.no_of_ratings || 0 %></span> Rating</p>
						</div>
						<div class="item_description_div_cost">
							<p class="item_description_div_cost_value"> $<%=@dish.cost || 0%>  </p>
						</div>
						<% if @dish.user == current_or_guest_user %>
							<div class="item_description_div_cost_edit">
								<p class="item_description_div_cost_value"> <%= link_to "Edit Dish", edit_dish_path(@dish), :class => "btn btn-danger header_btn edit_dish_btn", :id => "edit_dish" %> </p>
							</div>
						<% end %>
					</div>
				</div>
			</div>  
			<div class="row  row_item green_border">
				<div class="restaurant_address">
					<p class="address_text"><%= @dish.location_address %></p>
					<a href="#" class="right_anchor map_opener"> Show on map </a> 
				</div>
				<div class="row row_item map">
					<%#= @dish.location_address || "Velachery" %>
					<div id="map-canvas"></div>
				</div>
			</div>
		</div>
        
	</div>

	<div class="row item_info_box row_modify reviews_container">
		<div class="col-lg-12 reviews_top_bar">
			<p class="address_text">Write a review for <span class="color_green"><%=@dish.name.to_s.capitalize%></span> at <%=@dish.restaurant_name.to_s.capitalize%></p>
			<a href="#" class="right_anchor write_review"> Write review </a> 
			<p href="#" class="right_anchor_p"> <%= @dish.reviews.size - 1 %> reviews </p> 
		</div>
		<div class="review_pagination_controller">
			<% if @dish.reviews.size > 1 %>
			<%= render :partial => 'review', :collection => @dish.reviews, :as => :review %>
			<% end %>
		</div>

		<div class="col-lg-12 reviews_comment">
			<p class="comment_heading">
				WRITE A REVIEW FOR  <span class="color_green"><%=@dish.name.to_s.upcase %></span> AT <%=@dish.restaurant_name.to_s.upcase %>
			</p>
			<%= form_for(@new_review, remote: true) do |new_review| %>
        <div id="error_explanation">
        </div>
			<!-- <textarea class="commment_textarea"></textarea>  -->
			<%= new_review.text_area :description, :class => "commment_textarea" %>
			<%= new_review.hidden_field :dish_id, :value => @dish.id %>
			<button class="btn btn-success right_button">SUBMIT REVIEW</button>
				<%= new_rating %>
			<% end %>
		</div>

	</div>

</div>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script>
$('.map_opener').click(function()
{
	console.log('I am in map opener');
	if($('.map').is(':visible'))
	{
		// var height = $('.section_item').css('height') - $('.map').css('height');
		$('.map').slideUp();
		// $('.section_item').css('height',height);
	}
	else
	{
		// var height = $('.section_item').css('height') + $('.map').css('height');
		$('.map').slideDown();
		// $('.section_item').css('height',height);

		//If opening for the first Time, initialize GMaps
		if (!$('.map').data('rendered')) {
			showLocationOnMap("<%=@dish.location.latitude%>","<%=@dish.location.longitude%>");
			$('.map').data('rendered', true);
		}
	}

	return false;
});
</script>

app/views/dishes/show_old.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dish.name %>
</p>

<p>
  <b>User:</b>
  <%= @dish.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @dish.description %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @dish.restaurant_name %>
</p>

<p>
  <b>Avg points:</b>
  <%= @dish.avg_ratings %>
</p>

<p>
  <b>No of ratings:</b>
  <%= @dish.no_of_ratings %>
</p>

<p>
  <b>Image</b>
  <%= image_tag dish_show_image_path(@dish.id) %>
</p>

<p>
  <b>Awesomeness:</b>
  <%= rating_stars(@dish) %> <%= rating_average(@dish) %>
  No of people who rated : <%= awesomeness_qty(@dish) %>
</p>
<p>
  <% (@dish.tags || []).each do |tag| %>
    <b> "<%= tag.name %>" <b> 
  <% end %>
<p>
<p class="reviews_container">
  <% if @reviews %>
    <% @reviews.each do |review| %>
      <%= review.description %>
      <%#= review.user.name %>
      <%#= review.user.no_of_reviews %>
      <br />
    <% end %>
  <% end %>
</p>

<p>
  Add a review
  <%= form_for(@new_review, remote: true) do |new_review| %>
    <div class="field">
      <%= new_review.label :description %><br /> 
      <%= new_review.text_area :description %>
    <div>
      <%= new_review.hidden_field :dish_id, :value => @dish.id %>
      <%= new_review.submit %>
  <% end %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>